name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Build LambdaSharp.DynamoDB.Serialization
      - name: Restore LambdaSharp.DynamoDB.Serialization
        run: dotnet restore Source/LambdaSharp.DynamoDB.Serialization/LambdaSharp.DynamoDB.Serialization.csproj
      - name: Build LambdaSharp.DynamoDB.Serialization
        run: dotnet build --no-restore --configuration Release Source/LambdaSharp.DynamoDB.Serialization/LambdaSharp.DynamoDB.Serialization.csproj
      - name: Pack LambdaSharp.DynamoDB.Serialization
        run: dotnet pack --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o . Source/LambdaSharp.DynamoDB.Serialization/LambdaSharp.DynamoDB.Serialization.csproj

      # Build LambdaSharp.DynamoDB.Native
      - name: Restore LambdaSharp.DynamoDB.Native
        run: dotnet restore Source/LambdaSharp.DynamoDB.Native/LambdaSharp.DynamoDB.Native.csproj
      - name: Build LambdaSharp.DynamoDB.Native
        run: dotnet build --no-restore --configuration Release Source/LambdaSharp.DynamoDB.Native/LambdaSharp.DynamoDB.Native.csproj
      - name: Pack LambdaSharp.DynamoDB.Native
        run: dotnet pack --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o . Source/LambdaSharp.DynamoDB.Native/LambdaSharp.DynamoDB.Native.csproj

      # Build Samples
      - name: Build DynamoDBNativeSample Sample
        run: dotnet build Samples/DynamoDBNativeSample/Sample.DynamoDBNative.DataAccess/Sample.DynamoDBNative.DataAccess.csproj

      # Publish Packages
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
